name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer

jobs:
  test:
    name: Test with xcodebuild
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    
    - name: Run tests with xcodebuild
      run: xcodebuild -scheme LeakedViewControllerDetector -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' test 